### ISSUE TITLE
Please change paste behavior 

### ISSUE THREAD

**Issue by artkrz** [zerowidth/camper_van#18] opened 2012-10-25 10:37 UTC
Hello,

Grate job. Super simple and works but can you implement past links instead of text ? Or a shortend paste + links, on long paste the chat gets flooded.

Thanks

**Comment by zerowidth** [comment] 2012-10-27 22:09
The Paste message handling splits any incoming text on "\n" and sends the first three lines to IRC. If there are more, it should include a link to the rest. Is three lines too much? It seemed like a good balance for short-ish messages but not hiding information behind a click.

**Comment by artkrz** [comment] 2012-10-29 07:57
I think on a very long paste it'll split it up and put multiple paste urls to different parts of paste, but that might be campfire behavior.

**Comment by artkrz** [comment] 2012-10-31 08:01
Actually it doesn't work as expected, please check screenshot. I've pasted a long source into textual.

![Screenshot](https://www.evernote.com/shard/s23/sh/7aed30dd-725f-4d79-a311-61ba00570ce6/42b4604a1e776398bed8781de03bb9e4/res/ae48137d-5a67-4557-bcba-3cec3d3de9e2/skitch.png)

**Comment by zerowidth** [comment] 2012-10-31 13:06
Ohh, I understand now. You're pasting code into your irc client, not displaying pastes.

The problem is, irc (and probably uour irc client as well) has no way of knowing that what you're about to paste into your client is many lines long. It's just a lot of sinle lines of text. Do you have any suggestions? A custom IRC command to indicate a section to get rolled up as a paste?

**Comment by zerowidth** [comment] 2013-02-17 21:27
Closing pending additional feedback.

**Closed as completed by zerowidth** 2013-02-17 21:27 UTC

**Comment by jimeh** [comment] 2013-07-18 12:02
My suggestion would be for camper_van to treat messages coming within a ms or so of each other from an IRC client (not from Campfire) as a single paste. Cause realistically you'll never be able to type as fast as the IRC client can send each line as a message of a pasted piece of text.

**Comment by coredump** [comment] 2013-11-03 04:45
I think @jimeh idea is the only feasible one.
